### PR TITLE
Add .travis.yml for Travis CI

### PR DESCRIPTION
**Pull request by ePirat**
This adds continuous integration through [Travis CI](https://travis-ci.org/)

An example can be found here: https://travis-ci.org/ePirat/libplacebo

### CODE REVIEW

**Comment by haasn** [comment]
A few comments:

1. `ninja test` does nothing unless you append `-Dtests=true` to the `meson` step.
2. wgetting a fixed release version of the ninja command like that seems suspect. Likely nobody will ever think to update this URL. How do we avoid it becoming stale?

**Comment by haasn** [comment]
Seems the version of ninja in the trusty repos is _way_ too old. We might still be able to add a PPA though, which would have a better chance of staying up-to-date than some random hard-coded URL.

**Comment by ePirat** [comment]
I don't think hardcoding a URL is a big problem. If it ever is too old to work with changes in your ninja build file, it will fail and we will notice and update it, no? I agree it is far from perfect. If you find a PPA that we can use, let me know and I'll give it a try.

**Comment by haasn** [comment]
Yeah, fair enough. After all, this is just for testing - as long as the test environment builds, the version is fine. It's not like we're distributing a binary or something; and performance+bug fixes most likely don't affect us.

**Pull request closed without merging**
